<?php 
function tpl_1223147562_1_1_13pagedevhtm6f863b8006315479bc8613b142d5f6bd( $tpl, $ctx ) {
$glb = $tpl->getGlobalContext() ;
$ctx->setXmlDeclaration('<?xml version="1.0" encoding="utf-8"?>') ;
?>
 <?php $ctx->setDocType('<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">'); ?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="cs" lang="cs">
    <head>
    	<script type="text/javascript" src="/js/js.js"></script>
    	<title><?php echo phptal_escape(phptal_path($ctx->SELF, 'page/title'), ENT_QUOTES, 'UTF-8') ?></title>
	</head>
    <body>
        <h1><?php echo phptal_escape(phptal_path($ctx->SELF, 'page/heading'), ENT_QUOTES, 'UTF-8') ?></h1>
        <p>
            testovaci odstavec
        </p>
        <p><?php echo $tpl->getTranslator()->translate('test');; ?></p>
		<?php echo $ctx->SELF->getComponentById("box_inquiries")->getContent() ?>
    </body>
</html><?php 
}

 ?><?php /* Generated by PHPTAL from /windows/H/www/lbox/project/templates/pages/_page_dev.html */; ?>