<?php 
function tpl_1223147562_1_1_13boxinquiricf041ca7dc44f556f4cac369fbe12918( $tpl, $ctx ) {
$glb = $tpl->getGlobalContext() ;
?><div class="box inquiries" id="box_inquiries">
	<h2>Anketa:</h2>
	<div class="box-body">
		<?php if ($ctx->inquiry): ; ?><div class="inquiry">
			<span class="question"><?php echo phptal_escape(phptal_path($ctx->inquiry, 'question'), ENT_QUOTES, 'UTF-8') ?></span>
			<ul class="options">
				<?php 
$__repeat__ = $ctx->repeat ;
$__repeat__->option = new PHPTAL_RepeatController(phptal_path($ctx->inquiry, 'getOptionsResponses')) ;
foreach ($__repeat__->option as $__key__ => $ctx->option ): ;
?><li class="option">
					<span class="text"><?php echo phptal_escape(phptal_path($ctx->option, 'answer'), ENT_QUOTES, 'UTF-8') ?></span>
					<span class="responses_count"><?php echo phptal_escape(''.phptal_path($ctx->option, 'count_responses_option').'/'.phptal_path($ctx->option, 'count_responses_inquiry').'', ENT_QUOTES, 'UTF-8') ?></span>
					<!--span class="responses_count" 	tal:content="string:${option/count_responses_option}" / -->
					<!--span class="responses_percent" tal:content="string:(${option/responses_option_percent}%)" / -->
					<div class="scale-container">
						<div class="scale" style="width: <?php echo phptal_escape(phptal_path($ctx->option, 'responses_option_percent', true), ENT_QUOTES, 'UTF-8');?>%;">
							<div class="normal">
								<div class="lft"><div class="rgt"><div class="mdl">&nbsp;</div></div></div>
							</div>
						</div>
						<?php if (!(phptal_path($ctx->inquiry, 'didUserVotedFor'))): ; ?><?php echo phptal_path($ctx->option, 'getForm') ?><?php endif; ?>
					</div>
				</li><?php endforeach; ?>
			</ul>
		</div><?php endif; ?>
		<?php if (!($ctx->inquiry)): ; ?><p>Nenalezena žádná anketa</p><?php endif; ?>
	</div>
	<div class="box-footer"></div>
</div><?php 
}

 ?><?php /* Generated by PHPTAL from /windows/H/www/lbox/project/templates/components/box_inquiries.html */; ?>