<?php 
function tpl_1223147562_1_1_13menumainht32e48b2fba0cb0987301dd1336198521_menu_list( $tpl, $ctx ) {
$tpl = clone $tpl ;
$ctx = $tpl->getContext() ;
$glb = $tpl->getGlobalContext() ;
$ctx = $tpl->pushContext() ;
$ctx->iterator = phptal_path($ctx->node, 'getChildren') ;
?><ul>
      <?php 
$__repeat__ = $ctx->repeat ;
$__repeat__->node = new PHPTAL_RepeatController($ctx->iterator) ;
foreach ($__repeat__->node as $__key__ => $ctx->node ): ;
?>
        <?php 
if (phptal_path($ctx->node, 'in_menu')):  ;
$ctx->noThrow(true) ;
if (!phptal_isempty($__ATT_class = phptal_path($ctx->node, 'getClass', true))):  ;
$__ATT_class = ' class="'.phptal_escape($__ATT_class, ENT_QUOTES, 'UTF-8').'"' ;
else:  ;
$__ATT_class = '' ;
endif ;
$ctx->noThrow(false) ;
?><li<?php echo $__ATT_class ?>>
           <?php 
if (!(phptal_path($ctx->node, 'isCurrent'))):  ;
$__att_href = phptal_escape(phptal_path($ctx->node, 'url'), ENT_QUOTES, 'UTF-8') ;
$__att_title = phptal_escape(phptal_path($ctx->node, 'titleMenu'), ENT_QUOTES, 'UTF-8') ;
?><a href="<?php echo $__att_href ?>" title="<?php echo $__att_title ?>">
              <span class="lft"><span class="rgt"><span class="mdl"><?php echo phptal_escape(phptal_path($ctx->node, 'name_menu'), ENT_QUOTES, 'UTF-8') ?></span></span></span>
           </a><?php endif; ?>
           <?php if (phptal_path($ctx->node, 'isCurrent')): ; ?><strong>
              <span class="lft"><span class="rgt"><span class="mdl"><?php echo phptal_escape(phptal_path($ctx->node, 'name_menu'), ENT_QUOTES, 'UTF-8') ?></span></span></span>
           </strong><?php endif; ?>
           <?php 
if (phptal_path($ctx->node, 'hasChildrenInMenu')):  ;
$ctx->pushSlots() ;
tpl_1223147562_1_1_13menumainht32e48b2fba0cb0987301dd1336198521_menu_list($tpl, $ctx) ;
$ctx->popSlots() ;
endif ;
?>
        </li><?php endif; ?>
      <?php endforeach; ?>
   </ul><?php 
$ctx = $tpl->popContext() ;

}

?><?php 
function tpl_1223147562_1_1_13menumainht32e48b2fba0cb0987301dd1336198521( $tpl, $ctx ) {
$glb = $tpl->getGlobalContext() ;
$ctx = $tpl->pushContext() ;
$ctx->iterator = $ctx->pages ;
?><div id="menumain">
   <h2>Navigace</h2>
   <ul>
      <?php 
$__repeat__ = $ctx->repeat ;
$__repeat__->node = new PHPTAL_RepeatController($ctx->iterator) ;
foreach ($__repeat__->node as $__key__ => $ctx->node ): ;
?>
        <?php 
if (phptal_path($ctx->node, 'in_menu')):  ;
$ctx->noThrow(true) ;
if (!phptal_isempty($__ATT_class = phptal_path($ctx->node, 'getClass', true))):  ;
$__ATT_class = ' class="'.phptal_escape($__ATT_class, ENT_QUOTES, 'UTF-8').'"' ;
else:  ;
$__ATT_class = '' ;
endif ;
$ctx->noThrow(false) ;
?><li<?php echo $__ATT_class ?>>
           <?php 
if (!(phptal_path($ctx->node, 'isCurrent'))):  ;
$__att_href = phptal_escape(phptal_path($ctx->node, 'url'), ENT_QUOTES, 'UTF-8') ;
$__att_title = phptal_escape(phptal_path($ctx->node, 'titleMenu'), ENT_QUOTES, 'UTF-8') ;
?><a href="<?php echo $__att_href ?>" title="<?php echo $__att_title ?>">
              <span class="lft"><span class="rgt"><span class="mdl"><?php echo phptal_escape(phptal_path($ctx->node, 'name_menu'), ENT_QUOTES, 'UTF-8') ?></span></span></span>
           </a><?php endif; ?>
           <?php if (phptal_path($ctx->node, 'isCurrent')): ; ?><strong>
              <span class="lft"><span class="rgt"><span class="mdl"><?php echo phptal_escape(phptal_path($ctx->node, 'name_menu'), ENT_QUOTES, 'UTF-8') ?></span></span></span>
           </strong><?php endif; ?>
           <?php 
if (phptal_path($ctx->node, 'hasChildrenInMenu')):  ;
$ctx->pushSlots() ;
tpl_1223147562_1_1_13menumainht32e48b2fba0cb0987301dd1336198521_menu_list($tpl, $ctx) ;
$ctx->popSlots() ;
endif ;
?>
        </li><?php endif; ?>
      <?php endforeach; ?>
   </ul>
    
</div><?php 
$ctx = $tpl->popContext() ;

}

?><?php /* Generated by PHPTAL from /windows/H/www/lbox/project/templates/components/menu_main.html */; ?>