<?php 
function tpl_1223147562_1_1_13defaulthtmd6454cfa3573baba8af575ddd22e7ae2( $tpl, $ctx ) {
$glb = $tpl->getGlobalContext() ;
$ctx->setDocType('<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">') ;
?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="cs" lang="cs">
    <head>
    <meta http-equiv="Content-type" content="application/xhtml+xml; charset=utf-8"/>
    <title><?php echo phptal_escape(phptal_path($ctx->SELF, 'page/title'), ENT_QUOTES, 'UTF-8') ?></title>
    <link rel="stylesheet" href="/css/css.css" type="text/css"/>
    <!--[if lte IE 6]>
        <link rel="stylesheet" href="/css/css-ie6.css" type="text/css" media="screen" />
    <![endif]-->
    <!--[if IE 7]>
        <link rel="stylesheet" href="/css/css-ie7.css" type="text/css" media="screen" />
    <![endif]-->
	<?php if (phptal_exists($ctx, 'SELF/page/rssPage')): ; ?><link rel="alternate" type="application/rss+xml" href="<?php echo phptal_escape(phptal_path($ctx->SELF, 'page/rssPage/url', true), ENT_QUOTES, 'UTF-8');?>" title="<?php echo phptal_escape(phptal_path($ctx->SELF, 'page/rssPage/title', true), ENT_QUOTES, 'UTF-8');?>"/><?php endif; ?>
	</head>
    <body>
		<?php echo $ctx->SELF->getComponentById("menu_main")->getContent() ?>
		<?php echo $ctx->SELF->templateGetSlot("content") ?>
    </body>
</html><?php 
}

 ?><?php /* Generated by PHPTAL from /windows/H/www/lbox/project/templates/layouts/default.html */; ?>