<?php 
function tpl_1223147562_1_1_13lboxformco6af4efba7676057571f619fbcb3e2d14( $tpl, $ctx ) {
$glb = $tpl->getGlobalContext() ;
$ctx = $tpl->pushContext() ;
$ctx->id = 'frm-'.phptal_path($ctx->SELF, 'getForm/getName').'-ctrl-'.phptal_path($ctx->SELF, 'getName').'' ;
?><div class="control">
	<?php 
$ctx->noThrow(true) ;
if (!phptal_isempty($__ATT_value = phptal_path($ctx->SELF, 'getValue', true))):  ;
$__ATT_value = ' value="'.phptal_escape($__ATT_value, ENT_QUOTES, 'UTF-8').'"' ;
elseif (NULL !== ($__ATT_value = phptal_path($ctx->SELF, 'getDefault', true))):  ;
$__ATT_value = ' value="'.phptal_escape($__ATT_value, ENT_QUOTES, 'UTF-8').'"' ;
endif ;
$ctx->noThrow(false) ;
$ctx->noThrow(true) ;
if (!phptal_isempty($__ATT_maxlength = phptal_path($ctx->SELF, 'getLengthMax', true))):  ;
$__ATT_maxlength = ' maxlength="'.phptal_escape($__ATT_maxlength, ENT_QUOTES, 'UTF-8').'"' ;
else:  ;
$__ATT_maxlength = '' ;
endif ;
$ctx->noThrow(false) ;
$ctx->noThrow(true) ;
if (!phptal_isempty($__ATT_size = phptal_path($ctx->SELF, 'getLengthMax', true))):  ;
$__ATT_size = ' size="'.phptal_escape($__ATT_size, ENT_QUOTES, 'UTF-8').'"' ;
else:  ;
$__ATT_size = '' ;
endif ;
$ctx->noThrow(false) ;
$ctx->noThrow(true) ;
if (!phptal_isempty($__ATT_disabled = phptal_path($ctx->SELF, 'getDisabled', true))):  ;
$__ATT_disabled = ' disabled="'.phptal_escape($__ATT_disabled, ENT_QUOTES, 'UTF-8').'"' ;
else:  ;
$__ATT_disabled = '' ;
endif ;
$ctx->noThrow(false) ;
?><input class="hidden" type="hidden" id="<?php echo phptal_escape($ctx->id, ENT_QUOTES, 'UTF-8');?>" name="<?php echo phptal_escape(phptal_path($ctx->SELF, 'getForm/getName', true), ENT_QUOTES, 'UTF-8');?>[<?php echo phptal_escape(phptal_path($ctx->SELF, 'getName', true), ENT_QUOTES, 'UTF-8');?>]"<?php echo $__ATT_value ?><?php echo $__ATT_maxlength ?><?php echo $__ATT_size ?><?php echo $__ATT_disabled ?>/>
	<?php 
$ctx = $tpl->pushContext() ;
$ctx->exceptions = phptal_path($ctx->SELF, 'getExceptionsValidations') ;
if (phptal_path($ctx->SELF, 'getExceptionsValidations')):  ;
?><div class="error">
		<?php 
$__repeat__ = $ctx->repeat ;
$__repeat__->exception = new PHPTAL_RepeatController($ctx->exceptions) ;
foreach ($__repeat__->exception as $__key__ => $ctx->exception ): ;
?>
			<div>vyhozena vyjimka validatoru:
						<font style="background: #0000ff; color: #ffffff"><?php echo phptal_escape(phptal_path($ctx->exception, 'getFile', true), ENT_QUOTES, 'UTF-8');?></font>
			cislo: 		<font style="background: #00ff00; color: #ffffff"><?php echo phptal_escape(phptal_path($ctx->exception, 'getCode', true), ENT_QUOTES, 'UTF-8');?></font>
			s hlaskou: 	<font style="background: #ff0000; color: #ffffff"><?php echo phptal_escape(phptal_path($ctx->exception, 'getMessage', true), ENT_QUOTES, 'UTF-8');?></font>
			</div>
		<?php endforeach; ?>
	</div><?php 
endif ;
$ctx = $tpl->popContext() ;
?>
</div><?php 
$ctx = $tpl->popContext() ;

}

?><?php /* Generated by PHPTAL from /windows/H/www/lbox/project/templates/forms/controls/lbox_form_control_fill_hidden.html */; ?>