<?php 
function tpl_1223147562_1_1_13lboxformcoc0941501de1b40cd2b5bde189be2eeb4( $tpl, $ctx ) {
$glb = $tpl->getGlobalContext() ;
?><script type="text/javascript"><?php echo phptal_path($ctx->SELF, 'getJSLib') ?></script>
<script type="text/javascript"><?php echo phptal_path($ctx->SELF, 'getJSInit') ?></script>
<noscript>
	<p class="error">Pro použití formuláře je nutno mít zapnutý javascript.</p>
</noscript>
<?php 
$ctx = $tpl->pushContext() ;
$ctx->exceptions = phptal_path($ctx->SELF, 'getExceptionsValidations') ;
if (phptal_path($ctx->SELF, 'getExceptionsValidations')):  ;
?><div class="error">
	<?php if (phptal_exists($ctx, 'exceptions/17004')): ; ?><div>Prosím aktivujte javascript!</div><?php endif; ?>
</div><?php 
endif ;
$ctx = $tpl->popContext() ;

}

?><?php /* Generated by PHPTAL from /windows/H/www/lbox/project/templates/forms/controls/lbox_form_control_spamdefense.html */; ?>