<?php 
function tpl_1223147562_1_1_13pagetitlehb42aefa39bb0487441ffea0b38d1448e( $tpl, $ctx ) {
$glb = $tpl->getGlobalContext() ;
?><?php echo phptal_escape($ctx->SELF->templateSlotContentBegin(), ENT_QUOTES, 'UTF-8') ?>
	<h1><?php echo phptal_escape(phptal_path($ctx->SELF, 'page/heading'), ENT_QUOTES, 'UTF-8') ?></h1>
<?php echo phptal_escape($ctx->SELF->templateSlotContentEnd("content"), ENT_QUOTES, 'UTF-8') ?>
<?php echo $ctx->SELF->getComponentById("layout_default")->getContent() ?><?php 
}

 ?><?php /* Generated by PHPTAL from /windows/H/www/lbox/project/templates/pages/page_title.html */; ?>