<?php 
function tpl_1223147562_1_1_13lboxforminbc8b4e0f53f5f48390d4566c6de4b209( $tpl, $ctx ) {
$glb = $tpl->getGlobalContext() ;
?><form id="frm-<?php echo phptal_escape(phptal_path($ctx->SELF, 'getName', true), ENT_QUOTES, 'UTF-8');?>" method="<?php echo phptal_escape(phptal_path($ctx->SELF, 'getMethod', true), ENT_QUOTES, 'UTF-8');?>" action="">
	<div class="controls">
		<?php 
$__repeat__ = $ctx->repeat ;
$__repeat__->control = new PHPTAL_RepeatController(phptal_path($ctx->SELF, 'getControls')) ;
foreach ($__repeat__->control as $__key__ => $ctx->control ): ;
?>
			<?php if (!(phptal_path($ctx->control, 'isSpamDefense'))): ; ?>
				<?php if (!(phptal_path($ctx->control, 'isSubControl'))): ; ?><?php echo $ctx->control ?><?php endif; ?>
			<?php endif; ?>
		<?php endforeach; ?>
	</div>
	<input class="submit" type="submit" name="<?php echo phptal_escape(phptal_path($ctx->SELF, 'getName', true), ENT_QUOTES, 'UTF-8');?>[sent]" value="<?php echo phptal_escape(phptal_path($ctx->SELF, 'getLabelSubmit', true), ENT_QUOTES, 'UTF-8');?>"/>
</form>
<?php echo phptal_path($ctx->SELF, 'getControlSpamDefense') ?><?php 
}

 ?><?php /* Generated by PHPTAL from /windows/H/www/lbox/project/templates/forms/lbox_form_inquiries_votefor.html */; ?>